AGENT_PHOTO = "/assets/agent/photo_2026-06-06_00-51-06.webp"
AGENT_PHOTOS = [
    "/assets/agent/photo_2026-06-06_00-51-06.webp",
    "/assets/agent/photo_2026-06-06_00-51-10.webp",
    "/assets/agent/photo_2026-06-06_00-51-17.webp",
    "/assets/agent/photo_2026-06-06_00-51-44.webp",
    "/assets/agent/photo_2026-06-06_00-51-49.webp",
    "/assets/agent/photo_2026-06-06_00-51-53.webp",
    "/assets/agent/photo_2026-06-06_00-51-58.webp",
    "/assets/agent/photo_2026-06-06_00-52-01.webp",
    "/assets/agent/photo_2026-06-06_00-52-05.webp",
]

COUNTRY_DATA = {
    "turkey": {
        "hero_subtitle_ru": "Древняя история, лазурное побережье и восточное гостеприимство. От шумных базаров Стамбула до воздушных шаров Каппадокии.",
        "hero_subtitle_en": "Ancient history, turquoise coastline, and eastern hospitality. From Istanbul's bustling bazaars to Cappadocia's hot air balloons.",
        "advantages_ru": [
            ("🏖", "Пляжный отдых", "Более 8000 км береговой линии. Голубой флаг на 500+ пляжах. Температура воды +24–28°C в сезон."),
            ("🏛", "История и культура", "20 объектов ЮНЕСКО. Античные города Эфес, Троя, Пергам. Османская архитектура Стамбула."),
            ("💱", "Доступные цены", "В 2026 году курс лиры делает Турцию одним из самых бюджетных направлений. Отели All Inclusive от $40/ночь."),
            ("🍽", "Гастрономия", "Турецкая кухня — одна из трёх великих кухонь мира. Кебабы, мезе, баклава, турецкий чай и кофе."),
            ("🛍", "Шопинг", "Гранд-базар в Стамбуле — 4000 магазинов. Кожа, текстиль, ковры, золото, специи."),
            ("👨‍👩‍👧", "Семейный отдых", "All Inclusive отели с детскими клубами, аквапарками и анимацией. Безвизовый въезд."),
        ],
        "advantages_en": [
            ("🏖", "Beach Vacation", "Over 8000 km of coastline. Blue Flag on 500+ beaches. Water temperature +24–28°C in season."),
            ("🏛", "History & Culture", "20 UNESCO sites. Ancient cities of Ephesus, Troy, Pergamon. Ottoman architecture in Istanbul."),
            ("💱", "Affordable Prices", "In 2026, the lira exchange rate makes Turkey one of the most budget-friendly destinations. All Inclusive from $40/night."),
            ("🍽", "Gastronomy", "Turkish cuisine is one of the world's three great cuisines. Kebabs, meze, baklava, Turkish tea and coffee."),
            ("🛍", "Shopping", "Grand Bazaar in Istanbul — 4000 shops. Leather, textiles, carpets, gold, spices."),
            ("👨‍👩‍👧", "Family-Friendly", "All Inclusive hotels with kids' clubs, water parks, and animation. Visa-free entry."),
        ],
        "seasons_ru": [
            ("🌸", "Весна (апрель–май)", "+18–25°C", "Идеально для экскурсий. Цены умеренные. Цветение тюльпанов в Стамбуле."),
            ("☀️", "Лето (июнь–сентябрь)", "+28–38°C", "Пляжный сезон. Высокие цены. Бронировать за 3–4 месяца."),
            ("🍂", "Осень (октябрь–ноябрь)", "+20–28°C", "Бархатный сезон. Тёплое море, меньше туристов. Цены снижаются."),
            ("❄️", "Зима (декабрь–март)", "+5–16°C", "Низкий сезон. Минимальные цены. Горные лыжи в Улудаге и Эрджиесе."),
        ],
        "seasons_en": [
            ("🌸", "Spring (Apr–May)", "+18–25°C", "Ideal for sightseeing. Moderate prices. Tulip bloom in Istanbul."),
            ("☀️", "Summer (Jun–Sep)", "+28–38°C", "Beach season. High prices. Book 3–4 months ahead."),
            ("🍂", "Autumn (Oct–Nov)", "+20–28°C", "Velvet season. Warm sea, fewer tourists. Prices decrease."),
            ("❄️", "Winter (Dec–Mar)", "+5–16°C", "Low season. Minimal prices. Skiing in Uludag and Erciyes."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽70 000–110 000", ["Отель 3* / апартаменты: от ₽2 000/ночь", "Питание в lokanta: ₽300–600/чел", "Транспорт: автобусы, долмуши", "Пляжи: муниципальные (бесплатно)"]),
            ("💎 Комфорт", "₽140 000–250 000", ["Отель 4–5*: от ₽5 000/ночь", "All Inclusive / рестораны: ₽1 000–2 500/чел", "Трансфер из аэропорта, такси", "Экскурсии, аквапарки, яхтинг"]),
            ("👑 Премиум", "₽350 000+", ["Отель 5* Deluxe / вилла: от ₽15 000/ночь", "Частный трансфер, гид", "Рестораны премиум-класса", "VIP-яхтинг, вертолётные туры"]),
        ],
        "budget_en": [
            ("💰 Economy", "$700–1 100", ["3* hotel / apartment: from $20/night", "Local lokanta: $3–6/person", "Transport: buses, dolmus", "Beaches: public (free)"]),
            ("💎 Comfort", "$1 400–2 500", ["4–5* hotel: from $50/night", "All Inclusive / restaurants: $10–25/person", "Airport transfer, taxi", "Excursions, water parks, yachting"]),
            ("👑 Premium", "$3 500+", ["5* Deluxe / villa: from $150/night", "Private transfer, guide", "Premium restaurants", "VIP yachting, helicopter tours"]),
        ],
        "practical_ru": {
            "visa": "Безвизовый въезд до 90 дней для граждан РФ.",
            "currency": "Турецкая лира (TRY). Ориентировочно: 1₺ ≈ 3.5 рубля (июнь 2026). Доллары и евро принимают в туристических зонах.",
            "language": "Турецкий. В туристических зонах — английский, часто русский.",
            "transport": "Междугородние автобусы, внутренние авиарейсы, долмуши. Аренда авто от €25/день.",
            "safety": "Туристические зоны безопасны. Рекомендуется стандартная осторожность в крупных городах.",
            "internet": "Wi-Fi в отелях. Местная SIM-карта (Turkcell, Vodafone) — от $10 с 20 ГБ.",
        },
        "practical_en": {
            "visa": "Visa-free entry up to 90 days for Russian citizens.",
            "currency": "Turkish Lira (TRY). Approx. $1 ≈ 31₺ (June 2026). USD and EUR accepted in tourist areas.",
            "language": "Turkish. English widely spoken in tourist areas, often Russian.",
            "transport": "Intercity buses, domestic flights, dolmus. Car rental from €25/day.",
            "safety": "Tourist areas are safe. Standard caution advised in large cities.",
            "internet": "Wi-Fi in hotels. Local SIM (Turkcell, Vodafone) — from $10 with 20 GB.",
        },
        "faq_ru": [
            ("Нужна ли виза в Турцию?", "Нет. Безвизовый въезд до 90 дней для граждан РФ. Загранпаспорт должен действовать не менее 120 дней с даты въезда."),
            ("Какая валюта в Турции?", "Турецкая лира (TRY). Рекомендуем менять валюту в Турции — курс выгоднее. Доллары и евро принимают в туристических зонах."),
            ("Когда лучше ехать в Турцию?", "Для пляжного отдыха: июнь–сентябрь. Для экскурсий: апрель–май, октябрь. Зимой — горные лыжи."),
            ("Сколько стоит отдых в Турции в 2026?", "Эконом: от ₽70 000 на человека за неделю. Комфорт: от ₽140 000. Премиум: от ₽350 000. Цены на перелёт включены."),
            ("Где лучше отдыхать с детьми?", "Анталья и Бодрум — лучшие All Inclusive отели с детскими клубами. Аланья — пологий вход в море."),
            ("Безопасно ли в Турции?", "Туристические зоны безопасны. Соблюдайте стандартные меры: не оставляйте вещи без присмотра на пляже."),
            ("Какой курорт выбрать?", "Анталья — универсальный. Бодрум — европейский стиль. Аланья — бюджетный. Каппадокия — экскурсионный. Стамбул — городской."),
            ("Нужно ли знать турецкий язык?", "Нет. В туристических зонах говорят по-русски и по-английски. Вывески часто на русском."),
            ("Что привезти из Турции?", "Специи, рахат-лукум, турецкий чай, керамику, кожу, текстиль, золото, кофе в турке."),
        ],
        "faq_en": [
            ("Do I need a visa for Turkey?", "Russian citizens: visa-free up to 90 days. Passport must be valid for at least 120 days from entry."),
            ("What currency is used in Turkey?", "Turkish Lira (TRY). Exchange in Turkey for better rates. USD and EUR accepted in tourist areas."),
            ("When is the best time to visit?", "Beach: June–September. Sightseeing: April–May, October. Winter: skiing in Uludag."),
            ("How much does a trip to Turkey cost in 2026?", "Economy: from $700/person per week. Comfort: from $1 400. Premium: from $3 500. Flights included."),
            ("Where to go with children?", "Antalya and Bodrum — best All Inclusive hotels with kids' clubs. Alanya — shallow beach entry."),
            ("Is Turkey safe?", "Tourist areas are safe. Follow standard precautions: don't leave valuables unattended on the beach."),
            ("Which resort to choose?", "Antalya — universal. Bodrum — European style. Alanya — budget. Cappadocia — sightseeing. Istanbul — city break."),
            ("Do I need to speak Turkish?", "No. English and Russian are widely spoken in tourist areas. Signs are often in Russian."),
            ("What souvenirs to bring?", "Spices, Turkish delight, tea, ceramics, leather, textiles, gold, Turkish coffee."),
        ],
        "what_to_see_ru": ["Айя-София и Голубая мечеть (Стамбул)", "Воздушные шары Каппадокии", "Античный Эфес", "Памуккале — белые травертины", "Пляж Клеопатры (Аланья)", "Замок Святого Петра (Бодрум)"],
        "what_to_see_en": ["Hagia Sophia & Blue Mosque (Istanbul)", "Cappadocia hot air balloons", "Ancient Ephesus", "Pamukkale white travertines", "Cleopatra Beach (Alanya)", "St. Peter's Castle (Bodrum)"],
        "where_to_stay_ru": [
            ("Султанахмет (Стамбул)", "Исторический центр. Для любителей экскурсий. Отели 3–5*, от €40/ночь."),
            ("Лара (Анталья)", "Пляжная зона с All Inclusive отелями. Для семей и пакетного отдыха. Отели 5*, от €60/ночь."),
            ("Гюмбет (Бодрум)", "Молодёжный район с барами и клубами. Для тусовок. Отели 3–4*, от €30/ночь."),
        ],
        "where_to_stay_en": [
            ("Sultanahmet (Istanbul)", "Historic center. For sightseeing. 3–5* hotels, from €40/night."),
            ("Lara (Antalya)", "Beach area with All Inclusive hotels. For families and package tours. 5* hotels, from €60/night."),
            ("Gumbet (Bodrum)", "Youth area with bars and clubs. For nightlife. 3–4* hotels, from €30/night."),
        ],
    },
    "thailand": {
        "hero_subtitle_ru": "Бирюзовое море, буддийские храмы и улыбки. От небоскрёбов Бангкока до нетронутых пляжей Краби.",
        "hero_subtitle_en": "Turquoise sea, Buddhist temples, and smiles. From Bangkok skyscrapers to untouched Krabi beaches.",
        "advantages_ru": [
            ("🏖", "Райские пляжи", "Андаманское море и Сиамский залив. Острова Пхи-Пхи, Самуи, Пхукет. Белый песок, пальмы."),
            ("💰", "Доступный отдых", "Цены в 2–3 раза ниже европейских. Уличная еда от $1. Массаж от $5."),
            ("🛕", "Культура и храмы", "Более 40 000 буддийских храмов. Королевский дворец в Бангкоке. Белый храм в Чианграе."),
            ("🤿", "Дайвинг и снорклинг", "Одни из лучших дайв-сайтов мира. Симиланские острова, Ко Тао. Китовые акулы, манты."),
            ("🧘", "Оздоровление", "Массаж, йога, детокс-программы. Тайский массаж признан ЮНЕСКО нематериальным наследием."),
        ],
        "advantages_en": [
            ("🏖", "Paradise Beaches", "Andaman Sea & Gulf of Thailand. Phi Phi Islands, Samui, Phuket. White sand, palm trees."),
            ("💰", "Affordable", "2–3x cheaper than Europe. Street food from $1. Massage from $5."),
            ("🛕", "Culture & Temples", "Over 40 000 Buddhist temples. Grand Palace in Bangkok. White Temple in Chiang Rai."),
            ("🤿", "Diving & Snorkeling", "World-class dive sites. Similan Islands, Koh Tao. Whale sharks, manta rays."),
            ("🧘", "Wellness", "Massage, yoga, detox programs. Thai massage recognized as UNESCO intangible heritage."),
        ],
        "seasons_ru": [
            ("☀️", "Высокий сезон (ноябрь–март)", "+28–33°C", "Сухо, солнечно. Идеальная погода. Цены максимальные. Бронировать за 3–4 месяца."),
            ("🔥", "Жаркий сезон (апрель–май)", "+30–38°C", "Очень жарко. Цены снижаются. Тайский Новый год (Сонгкран) в апреле."),
            ("🌧", "Сезон дождей (июнь–октябрь)", "+28–32°C", "Кратковременные ливни, в основном вечером. Самые низкие цены. Зелень и водопады."),
        ],
        "seasons_en": [
            ("☀️", "High Season (Nov–Mar)", "+28–33°C", "Dry and sunny. Perfect weather. Maximum prices. Book 3–4 months ahead."),
            ("🔥", "Hot Season (Apr–May)", "+30–38°C", "Very hot. Prices decrease. Thai New Year (Songkran) in April."),
            ("🌧", "Rainy Season (Jun–Oct)", "+28–32°C", "Short showers, mostly evening. Lowest prices. Lush greenery and waterfalls."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽90 000–140 000", ["Гестхаус / хостел: от ₽700/ночь", "Уличная еда: ₽100–300/чел", "Общественный транспорт, тук-туки", "Бесплатные пляжи, храмы"]),
            ("💎 Комфорт", "₽180 000–300 000", ["Отель 4*: от ₽3 500/ночь", "Рестораны среднего класса: ₽500–1 500/чел", "Такси, аренда байка", "Экскурсии на острова, дайвинг"]),
            ("👑 Премиум", "₽400 000+", ["Вилла / курорт 5*: от ₽15 000/ночь", "Fine dining, частный гид", "Аренда авто с водителем", "VIP-туры, спа-программы"]),
        ],
        "budget_en": [
            ("💰 Economy", "$900–1 400", ["Guesthouse / hostel: from $7/night", "Street food: $1–3/person", "Public transport, tuk-tuks", "Free beaches, temples"]),
            ("💎 Comfort", "$1 800–3 000", ["4* hotel: from $35/night", "Mid-range restaurants: $5–15/person", "Taxi, scooter rental", "Island excursions, diving"]),
            ("👑 Premium", "$4 000+", ["Villa / 5* resort: from $150/night", "Fine dining, private guide", "Car with driver", "VIP tours, spa programs"]),
        ],
        "practical_ru": {
            "visa": "Безвизовый въезд до 60 дней (с 2024). Можно продлить ещё на 30 дней в иммиграционном офисе.",
            "currency": "Тайский бат (THB). Ориентировочно: 1฿ ≈ 2.8 рубля (июнь 2026). Обменивайте в Таиланде — курс лучше.",
            "language": "Тайский. В туристических зонах — английский, частично русский.",
            "transport": "Метро/скайтрейн в Бангкоке, тук-туки, сонгтео, паромы. Аренда байка от ฿200/день.",
            "safety": "Очень безопасно для туристов. Остерегайтесь карманников в людных местах.",
            "internet": "Wi-Fi повсеместно. Местная SIM (AIS, TrueMove) — от ฿200 с безлимитным интернетом на 7 дней.",
        },
        "practical_en": {
            "visa": "Visa-free entry up to 60 days (since 2024). Can extend for another 30 days at immigration office.",
            "currency": "Thai Baht (THB). Exchange in Thailand for better rates.",
            "language": "Thai. English widely spoken in tourist areas, some Russian.",
            "transport": "BTS/MRT in Bangkok, tuk-tuks, songthaews, ferries. Scooter rental from ฿200/day.",
            "safety": "Very safe for tourists. Beware of pickpockets in crowded areas.",
            "internet": "Wi-Fi everywhere. Local SIM (AIS, TrueMove) — from ฿200 with unlimited internet for 7 days.",
        },
        "faq_ru": [
            ("Нужна ли виза в Таиланд?", "Гражданам РФ — безвизовый въезд до 60 дней (с 2024 года). Загранпаспорт должен действовать не менее 6 месяцев."),
            ("Какая валюта в Таиланде?", "Тайский бат (THB). Обменивайте в Таиланде, курс выгоднее. Карты принимают в крупных магазинах и отелях."),
            ("Когда лучше ехать в Таиланд?", "Ноябрь–март — высокий сезон, сухо. Апрель–май — жарко. Июнь–октябрь — дожди, но цены ниже."),
            ("Сколько стоит отдых в Таиланде?", "Эконом: от ₽90 000/чел. Комфорт: от ₽180 000. Премиум: от ₽400 000. Цены с перелётом."),
            ("Какой курорт выбрать?", "Пхукет — универсальный. Самуи — спокойный. Паттайя — тусовки. Краби — природа и скалы."),
            ("Безопасно ли в Таиланде?", "Очень безопасно для туристов. Таиланд — «страна улыбок». Осторожнее с арендой байка без прав."),
            ("Что попробовать из еды?", "Пад Тай, Том Ям, Сом Там, манго стики райс. Уличная еда безопасна — выбирайте оживлённые лотки."),
            ("Нужны ли прививки?", "Официально не требуются. Рекомендуется прививка от гепатита А и брюшного тифа."),
        ],
        "faq_en": [
            ("Do I need a visa for Thailand?", "Russian citizens: visa-free up to 60 days (since 2024). Passport valid for at least 6 months."),
            ("What currency is used?", "Thai Baht (THB). Exchange in Thailand for better rates."),
            ("When is the best time to visit?", "November–March: high season, dry. April–May: hot. June–October: rain, lower prices."),
            ("How much does a trip cost?", "Economy: from $900/person. Comfort: from $1 800. Premium: from $4 000. Flights included."),
            ("Which resort to choose?", "Phuket — universal. Samui — relaxed. Pattaya — nightlife. Krabi — nature and cliffs."),
            ("Is Thailand safe?", "Very safe for tourists. Thailand is the 'Land of Smiles'. Be careful with scooter rental without a license."),
            ("What food to try?", "Pad Thai, Tom Yum, Som Tam, Mango Sticky Rice. Street food is safe — choose busy stalls."),
            ("Do I need vaccinations?", "Not officially required. Hepatitis A and typhoid recommended."),
        ],
        "what_to_see_ru": ["Большой дворец (Бангкок)", "Острова Пхи-Пхи", "Белый храм (Чианграй)", "Древний город Аюттхая", "Водопад Эраван (Канчанабури)", "Дайвинг на Симиланах"],
        "what_to_see_en": ["Grand Palace (Bangkok)", "Phi Phi Islands", "White Temple (Chiang Rai)", "Ancient Ayutthaya", "Erawan Waterfall", "Similan Islands diving"],
        "where_to_stay_ru": [
            ("Сукхумвит (Бангкок)", "Деловой и развлекательный центр. Для молодёжи и шопинга. Отели 4–5*, от ฿1 500/ночь."),
            ("Ката/Карон (Пхукет)", "Спокойные пляжи, хорошая инфраструктура. Для семей. Отели 3–5*, от ฿1 200/ночь."),
            ("Чавенг (Самуи)", "Главный пляж острова с ресторанами и барами. Универсальный. Отели 3–5*, от ฿1 000/ночь."),
        ],
        "where_to_stay_en": [
            ("Sukhumvit (Bangkok)", "Business & entertainment hub. For youth and shopping. 4–5* hotels, from ฿1 500/night."),
            ("Kata/Karon (Phuket)", "Quiet beaches, good infrastructure. For families. 3–5* hotels, from ฿1 200/night."),
            ("Chaweng (Samui)", "Main island beach with restaurants and bars. Universal. 3–5* hotels, from ฿1 000/night."),
        ],
    },
    "egypt": {
        "hero_subtitle_ru": "Древние пирамиды, Красное море и круглогодичное солнце. От коралловых рифов Шарм-эль-Шейха до сокровищ Луксора.",
        "hero_subtitle_en": "Ancient pyramids, the Red Sea, and year-round sunshine. From Sharm El Sheikh coral reefs to Luxor's treasures.",
        "advantages_ru": [
            ("🤿", "Дайвинг и снорклинг", "Красное море — одно из лучших мест для дайвинга в мире. Коралловые рифы, затонувшие корабли. Видимость до 30 метров."),
            ("🏛", "Древняя история", "Пирамиды Гизы — единственное сохранившееся чудо света. Луксор и Карнак — крупнейший музей под открытым небом."),
            ("☀️", "Круглый год", "Температура +22–35°C круглый год. Купальный сезон 12 месяцев."),
            ("💰", "Доступные цены", "All Inclusive отели от $35/ночь. Ужин в ресторане от $5. Цены в 2–3 раза ниже европейских курортов."),
            ("👨‍👩‍👧", "Семейный отдых", "Большинство отелей — семейные. Мелкие песчаные пляжи. Анимация на русском языке."),
        ],
        "advantages_en": [
            ("🤿", "Diving & Snorkeling", "The Red Sea — world's best diving. Coral reefs, shipwrecks. Visibility up to 30m."),
            ("🏛", "Ancient History", "Pyramids of Giza — only surviving wonder. Luxor — world's largest open-air museum."),
            ("☀️", "Year-Round", "+22–35°C all year. Swimming season 12 months."),
            ("💰", "Affordable", "All Inclusive from $35/night. Restaurant dinner from $5. 2–3x cheaper than European resorts."),
            ("👨‍👩‍👧", "Family-Friendly", "Most hotels are family-oriented. Shallow sandy beaches. Russian animation."),
        ],
        "seasons_ru": [
            ("☀️", "Высокий сезон (октябрь–апрель)", "+22–28°C", "Идеальная погода. Цены максимальные. Бронировать за 3–4 месяца."),
            ("🔥", "Лето (май–сентябрь)", "+30–40°C", "Очень жарко. Цены падают на 40–50%. Вода тёплая, но освежает."),
        ],
        "seasons_en": [
            ("☀️", "High Season (Oct–Apr)", "+22–28°C", "Perfect weather. Maximum prices. Book 3–4 months ahead."),
            ("🔥", "Summer (May–Sep)", "+30–40°C", "Very hot. Prices drop 40–50%."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽60 000–100 000", ["Отель 3*: от ₽1 500/ночь", "Питание в кафе: от ₽300/чел", "Общественный транспорт", "Бесплатные муниципальные пляжи"]),
            ("💎 Комфорт", "₽120 000–200 000", ["Отель 4–5* All Inclusive: от ₽4 000/ночь", "Рестораны, дайвинг-туры", "Трансфер из аэропорта", "Экскурсии в Луксор, на пирамиды"]),
            ("👑 Премиум", "₽250 000+", ["Отель 5* Deluxe: от ₽10 000/ночь", "VIP-дайвинг, яхтинг", "Индивидуальный гид", "Премиум-экскурсии, спа"]),
        ],
        "budget_en": [
            ("💰 Economy", "$600–1 000", ["3* hotel from $15/night", "Cafes from $3/person", "Public transport", "Free public beaches"]),
            ("💎 Comfort", "$1 200–2 000", ["4–5* All Inclusive from $40/night", "Restaurants, diving tours", "Airport transfer", "Luxor & pyramid excursions"]),
            ("👑 Premium", "$2 500+", ["5* Deluxe from $100/night", "VIP diving, yachting", "Private guide & transfer", "Premium excursions, spa"]),
        ],
        "practical_ru": {
            "visa": "Виза по прибытии для граждан РФ ($25). Или электронная виза заранее на visa2egypt.gov.eg.",
            "currency": "Египетский фунт (EGP). Ориентировочно: 1 EGP ≈ 1.8 рубля (июнь 2026). Доллары принимают повсеместно.",
            "language": "Арабский. В туристических зонах — русский и английский. Вывески на русском.",
            "transport": "Такси (Uber/Careem в Каире), маршрутки, внутренние рейсы.",
            "safety": "Туристические зоны безопасны. Не покидайте курортные зоны самостоятельно. Пейте бутилированную воду.",
            "internet": "Wi-Fi в отелях. Местная SIM — от $5 с 10 ГБ.",
        },
        "practical_en": {
            "visa": "Visa on arrival for Russian citizens ($25). E-visa at visa2egypt.gov.eg.",
            "currency": "Egyptian Pound (EGP). USD accepted everywhere.",
            "language": "Arabic. Russian & English in tourist areas.",
            "transport": "Taxi (Uber/Careem in Cairo), minibuses, domestic flights.",
            "safety": "Tourist areas safe. Don't leave resort zones alone. Drink bottled water.",
            "internet": "Wi-Fi in hotels. Local SIM from $5 with 10 GB.",
        },
        "faq_ru": [
            ("Нужна ли виза в Египет?", "Гражданам РФ — виза по прибытии ($25). Безвизовый въезд на Синай до 15 дней."),
            ("Когда лучше ехать в Египет?", "Октябрь–апрель — высокий сезон. Летом жарко, но цены на 40% ниже."),
            ("Какой курорт выбрать?", "Шарм-эль-Шейх — дайвинг. Хургада — пляжи и семьи. Марса-Алам — уединение."),
            ("Сколько стоит отдых в Египте?", "Эконом: от ₽60 000/чел. Комфорт: от ₽120 000. Премиум: от ₽250 000. Цены с перелётом."),
            ("Безопасно ли в Египте?", "На курортах безопасно. Пейте бутилированную воду. Не покидайте курортные зоны."),
            ("Что посмотреть кроме пляжа?", "Пирамиды Гизы, Луксор, Долина Царей, Александрия, монастырь Святой Екатерины."),
            ("Нужны ли прививки?", "Официально не требуются. Рекомендуется гепатит А."),
        ],
        "faq_en": [
            ("Do I need a visa?", "Russian citizens: visa on arrival ($25). Sinai: 15-day visa-free."),
            ("When to visit?", "October–April: high season. Summer hot but 40% cheaper."),
            ("Which resort?", "Sharm El Sheikh — diving. Hurghada — beaches. Marsa Alam — seclusion."),
            ("How much?", "Economy: from $600. Comfort: from $1 200. Premium: from $2 500. Estimates."),
            ("Is Egypt safe?", "Safe on resorts. Drink bottled water."),
            ("What to see?", "Pyramids, Luxor, Valley of the Kings, Alexandria, St. Catherine's."),
            ("Vaccinations?", "Not required. Hepatitis A recommended."),
        ],
        "what_to_see_ru": ["Пирамиды Гизы и Сфинкс", "Луксорский храм и Карнак", "Гора Моисея (Синай)", "Цветной каньон", "Монастырь Святой Екатерины", "Коралловые рифы Рас-Мохаммед"],
        "what_to_see_en": ["Pyramids of Giza & Sphinx", "Luxor Temple & Karnak", "Mount Sinai", "Colored Canyon", "St. Catherine's Monastery", "Ras Mohammed reefs"],
        "where_to_stay_ru": [
            ("Наама-Бей (Шарм)", "Центральный район с ресторанами. Отели 4–5* от $35/ночь."),
            ("Сахль-Хашиш (Хургада)", "Элитный район с песчаными пляжами. Отели 5* от $50/ночь."),
            ("Эль-Гуна (Хургада)", "Курорт на каналах. Для молодёжи и кайтсёрферов. Отели 3–5* от $30/ночь."),
        ],
        "where_to_stay_en": [
            ("Naama Bay (Sharm)", "Central area. 4–5* hotels from $35/night."),
            ("Sahl Hasheesh (Hurghada)", "Premium beach area. 5* hotels from $50/night."),
            ("El Gouna (Hurghada)", "Resort on canals. 3–5* hotels from $30/night."),
        ],
    },
    "uae": {
        "hero_subtitle_ru": "Роскошные небоскрёбы, белоснежные пляжи и восточный колорит. От футуристичного Дубая до горных пейзажей Рас-эль-Хаймы.",
        "hero_subtitle_en": "Luxury skyscrapers, white sand beaches, and eastern charm. From futuristic Dubai to Ras Al Khaimah's mountain landscapes.",
        "advantages_ru": [
            ("🛡", "Безопасность", "ОАЭ входит в топ-3 самых безопасных стран мира. Уровень преступности близок к нулю."),
            ("🏖", "Пляжи и море", "Более 700 км побережья. Белый песок, бирюзовая вода. Температура воды +22–33°C."),
            ("🛍", "Шопинг мирового уровня", "Dubai Mall — крупнейший ТЦ мира. Ежегодный Shopping Festival. Tax Free."),
            ("🎢", "Развлечения", "Бурдж-Халифа, аквапарки, Ferrari World, сафари в пустыне, поющие фонтаны."),
            ("👨‍👩‍👧", "Семейный отдых", "Безопасно для детей. Детские зоны в каждом ТЦ, аквапарки, зоопарки."),
        ],
        "advantages_en": [
            ("🛡", "Safety", "Top-3 safest countries worldwide. Near-zero crime rate."),
            ("🏖", "Beaches & Sea", "700+ km of coastline. White sand, turquoise water."),
            ("🛍", "World-Class Shopping", "Dubai Mall — largest in the world. Annual Shopping Festival."),
            ("🎢", "Entertainment", "Burj Khalifa, water parks, Ferrari World, desert safari."),
            ("👨‍👩‍👧", "Family-Friendly", "Kids' zones, water parks, zoos. Hotels with kids' club."),
        ],
        "seasons_ru": [
            ("☀️", "Высокий сезон (ноябрь–март)", "+24–28°C", "Идеальная погода. Цены максимальные. Бронировать за 2–3 месяца."),
            ("🌸", "Переходный (апрель, октябрь)", "+28–35°C", "Комфортно, меньше туристов. Цены умеренные."),
            ("🔥", "Лето (май–сентябрь)", "+38–48°C", "Экстремальная жара. Цены падают на 50–70%. Фуджейра прохладнее."),
        ],
        "seasons_en": [
            ("☀️", "High Season (Nov–Mar)", "+24–28°C", "Perfect weather. Book 2–3 months ahead."),
            ("🌸", "Shoulder (Apr, Oct)", "+28–35°C", "Comfortable, fewer tourists."),
            ("🔥", "Summer (May–Sep)", "+38–48°C", "Extreme heat. Prices drop 50–70%."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽80 000–130 000", ["Отель 3*: от ₽3 000/ночь", "Фудкорты: от ₽500/чел", "Метро, автобусы", "Бесплатные пляжи JBR"]),
            ("💎 Комфорт", "₽180 000–350 000", ["Отель 4–5*: от ₽8 000/ночь", "Рестораны: от ₽2 000/чел", "Такси, аренда авто", "Бурдж-Халифа, аквапарки"]),
            ("👑 Премиум", "₽500 000+", ["Отель 5* Deluxe: от ₽25 000/ночь", "Fine dining, личный водитель", "VIP-туры, яхтинг", "Вертолётные прогулки"]),
        ],
        "budget_en": [
            ("💰 Economy", "$800–1 300", ["3* hotel from $30/night", "Food courts from $5/person", "Metro, buses", "Free JBR beaches"]),
            ("💎 Comfort", "$1 800–3 500", ["4–5* hotel from $80/night", "Restaurants from $20/person", "Taxi, car rental", "Burj Khalifa, water parks"]),
            ("👑 Premium", "$5 000+", ["5* Deluxe from $250/night", "Fine dining, personal driver", "VIP tours, yachting", "Helicopter tours"]),
        ],
        "practical_ru": {
            "visa": "Безвизовый въезд до 90 дней для РФ. Загранпаспорт — 6+ месяцев от даты въезда.",
            "currency": "Дирхам ОАЭ (AED). Ориентировочно: 1 AED ≈ 24 рубля (июнь 2026). Доллары и карты принимают везде.",
            "language": "Арабский (официальный). Английский — везде. Русский — в крупных отелях.",
            "transport": "Метро Дубая, такси (Careem/Uber), аренда авто от ₽3 500/день. Автобусы между эмиратами.",
            "safety": "Одна из самых безопасных стран. Строгие законы: алкоголь — в отелях, одежда — скромная.",
            "internet": "Wi-Fi везде. Местная SIM (Etisalat/Du) — от $15 с 10 ГБ.",
        },
        "practical_en": {
            "visa": "Visa-free 90 days for Russian citizens. Passport 6+ months valid.",
            "currency": "UAE Dirham (AED). USD & cards accepted everywhere.",
            "language": "Arabic (official). English everywhere. Russian in major hotels.",
            "transport": "Dubai Metro, taxi (Careem/Uber), car rental from $35/day.",
            "safety": "Very safe. Strict laws: alcohol in hotels, modest dress.",
            "internet": "Wi-Fi everywhere. Local SIM from $15 with 10 GB.",
        },
        "faq_ru": [
            ("Нужна ли виза в ОАЭ?", "Гражданам РФ — безвизовый въезд до 90 дней."),
            ("Какой эмират выбрать?", "Дубай — шопинг. Абу-Даби — культура. Шарджа — бюджет. Фуджейра — дайвинг. Рас-эль-Хайма — природа."),
            ("Когда лучше ехать?", "Ноябрь–март — идеально. Летом жарко (+38–48°C), но цены на 50% ниже."),
            ("Сколько стоит отдых?", "Эконом: от ₽80 000. Комфорт: от ₽180 000. Премиум: от ₽500 000. Ориентиры."),
            ("Безопасно ли в ОАЭ?", "Очень безопасно. Строгие законы соблюдайте."),
            ("Что нельзя делать?", "Фотографировать местных без разрешения. Алкоголь — в отелях."),
            ("Можно ли с детьми?", "Идеально. Аквапарки, зоопарки, детские зоны везде."),
        ],
        "faq_en": [
            ("Do I need a visa?", "Russian citizens: visa-free 90 days."),
            ("Which emirate?", "Dubai — shopping. Abu Dhabi — culture. Sharjah — budget. Fujairah — diving."),
            ("When to visit?", "November–March ideal. Summer hot but 50% cheaper."),
            ("How much?", "Economy: from $800. Comfort: from $1 800. Premium: from $5 000. Estimates."),
            ("Is UAE safe?", "Very safe. Respect strict laws."),
            ("What not to do?", "Don't photograph locals. Alcohol in hotels only."),
            ("Good for kids?", "Perfect. Water parks, zoos, kids' zones everywhere."),
        ],
        "what_to_see_ru": ["Бурдж-Халифа и Dubai Mall", "Мечеть шейха Зайда (Абу-Даби)", "Лувр Абу-Даби", "Сафари в пустыне", "Поющие фонтаны", "Аквапарк Aquaventure"],
        "what_to_see_en": ["Burj Khalifa & Dubai Mall", "Sheikh Zayed Mosque", "Louvre Abu Dhabi", "Desert safari", "Dubai Fountain", "Aquaventure"],
        "where_to_stay_ru": [
            ("Дубай Марина / JBR", "Пляжный район с променадом. Отели 4–5* от AED 400/ночь."),
            ("Корниш (Абу-Даби)", "Набережная с парками. Отели 5* от AED 500/ночь."),
            ("Аль-Хан (Шарджа)", "Бюджетный пляжный район. Отели 3–4* от AED 150/ночь."),
        ],
        "where_to_stay_en": [
            ("Dubai Marina / JBR", "Beachfront. 4–5* hotels from AED 400/night."),
            ("Corniche (Abu Dhabi)", "Waterfront. 5* hotels from AED 500/night."),
            ("Al Khan (Sharjah)", "Budget beach. 3–4* hotels from AED 150/night."),
        ],
    },
    "indonesia": {
        "hero_subtitle_ru": "Тысячи островов, древние храмы и джунгли. Бали — жемчужина архипелага: от рисовых террас Убуда до сёрф-пляжей Чангу.",
        "hero_subtitle_en": "Thousands of islands, ancient temples, and jungles. Bali — the jewel: from Ubud's rice terraces to Canggu's surf beaches.",
        "advantages_ru": [
            ("🏝", "Островное разнообразие", "17 000+ островов. Бали, Ява, Ломбок, Суматра. Каждый остров уникален."),
            ("🧘", "Духовный отдых", "Бали — центр йоги и медитации. Убуд — мировая столица wellness."),
            ("🏄", "Сёрфинг мирового уровня", "Волны для всех: от Куты (новички) до Улувату (профи). Круглый год."),
            ("🌿", "Уникальная природа", "Рисовые террасы, вулканы, водопады. Остров Комодо — драконы."),
            ("💰", "Доступный люкс", "Вилла с бассейном от $50/ночь. Массаж от $7. Ужин от $5."),
        ],
        "advantages_en": [
            ("🏝", "Island Diversity", "17 000+ islands. Each unique."),
            ("🧘", "Spiritual Retreat", "Bali — yoga & meditation hub."),
            ("🏄", "World-Class Surf", "All levels year-round."),
            ("🌿", "Unique Nature", "Rice terraces, volcanoes, Komodo dragons."),
            ("💰", "Affordable Luxury", "Pool villa from $50/night. Massage from $7."),
        ],
        "seasons_ru": [
            ("☀️", "Сухой сезон (апрель–октябрь)", "+27–32°C", "Лучшее время. Минимум дождей. Цены пик в июле–августе."),
            ("🌧", "Влажный сезон (ноябрь–март)", "+26–30°C", "Кратковременные ливни. Цены ниже на 20–30%."),
        ],
        "seasons_en": [
            ("☀️", "Dry Season (Apr–Oct)", "+27–32°C", "Best time. Prices peak July–August."),
            ("🌧", "Wet Season (Nov–Mar)", "+26–30°C", "Short showers. Prices 20–30% lower."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽80 000–130 000", ["Гестхаус: от ₽600/ночь", "Варунг (кафе): от ₽150/чел", "Аренда байка: от ₽350/день", "Бесплатные пляжи, храмы"]),
            ("💎 Комфорт", "₽160 000–280 000", ["Вилла 4*: от ₽4 000/ночь", "Рестораны: от ₽500/чел", "Авто с водителем", "Экскурсии на водопады, вулканы"]),
            ("👑 Премиум", "₽400 000+", ["Вилла 5*: от ₽15 000/ночь", "Fine dining, частный гид", "VIP-туры на Комодо", "Спа-ретриты, йога"]),
        ],
        "budget_en": [
            ("💰 Economy", "$800–1 300", ["Guesthouse from $6/night", "Warung from $1.50", "Scooter from $3.50/day", "Free beaches & temples"]),
            ("💎 Comfort", "$1 600–2 800", ["4* villa from $40/night", "Restaurants from $5/person", "Car with driver", "Waterfall & volcano excursions"]),
            ("👑 Premium", "$4 000+", ["5* villa from $150/night", "Fine dining, private guide", "VIP Komodo tours", "Spa retreats, yoga"]),
        ],
        "practical_ru": {
            "visa": "Виза по прибытии (500 000 IDR ≈ $33). 30 дней, продлеваемая.",
            "currency": "Индонезийская рупия (IDR). Крупные купюры — считайте нули.",
            "language": "Индонезийский. Английский на Бали. Русский редко.",
            "transport": "Аренда байка — основной транспорт. Такси (Gojek, Grab).",
            "safety": "Безопасно. Осторожнее на дорогах. Не пейте воду из-под крана.",
            "internet": "Wi-Fi в отелях. Местная SIM (Telkomsel) — от $5 с 10 ГБ.",
        },
        "practical_en": {
            "visa": "Visa on arrival (~$33). 30 days, extendable.",
            "currency": "Indonesian Rupiah (IDR). Count zeros carefully.",
            "language": "Indonesian. English in Bali. Russian rare.",
            "transport": "Scooter rental is primary. Taxi (Gojek, Grab).",
            "safety": "Safe. Road safety important. Don't drink tap water.",
            "internet": "Wi-Fi in hotels. Local SIM (Telkomsel) from $5.",
        },
        "faq_ru": [
            ("Нужна ли виза?", "Виза по прибытии на 30 дней (~$33). Можно продлить."),
            ("Когда лучше ехать на Бали?", "Апрель–октябрь — сухой сезон. Ноябрь–март — дешевле."),
            ("Какой район Бали выбрать?", "Убуд — йога. Кута — сёрфинг. Семиньяк — рестораны. Чангу — хипстеры. Нуса-Дуа — luxury."),
            ("Сколько стоит отдых?", "Эконом: от ₽80 000. Комфорт: от ₽160 000. Премиум: от ₽400 000. Ориентиры."),
            ("Безопасно ли на Бали?", "Очень безопасно. Основной риск — дороги."),
            ("Что попробовать?", "Наси горенг, сате, гадо-гадо, баби гулинг."),
        ],
        "faq_en": [
            ("Visa?", "Visa on arrival, 30 days (~$33). Extendable."),
            ("When to visit Bali?", "April–October dry season. November–March cheaper."),
            ("Which area?", "Ubud — yoga. Kuta — surf. Seminyak — dining. Canggu — hipster."),
            ("How much?", "Economy: from $800. Comfort: from $1 600. Premium: from $4 000."),
            ("Is Bali safe?", "Very safe. Main risk: road traffic."),
            ("What to eat?", "Nasi Goreng, Satay, Gado-Gado, Babi Guling."),
        ],
        "what_to_see_ru": ["Рисовые террасы Тегаллаланг", "Храм Улувату", "Вулкан Батур (рассвет)", "Водопады Секумпул", "Лес обезьян в Убуде", "Остров Комодо"],
        "what_to_see_en": ["Tegallalang rice terraces", "Uluwatu Temple", "Mount Batur sunrise", "Sekumpul waterfalls", "Ubud Monkey Forest", "Komodo Island"],
        "where_to_stay_ru": [
            ("Убуд", "Культурное сердце. Виллы от $30/ночь. Духовный отдых."),
            ("Семиньяк", "Премиальный. Рестораны и бутики. Виллы от $60/ночь."),
            ("Чангу", "Хипстерский сёрф. Кафе и коворкинги. От $10/ночь."),
        ],
        "where_to_stay_en": [
            ("Ubud", "Cultural heart. Villas from $30/night."),
            ("Seminyak", "Premium. Dining & boutiques. From $60/night."),
            ("Canggu", "Hipster surf. Cafes & coworking. From $10/night."),
        ],
    },
    "china": {
        "hero_subtitle_ru": "Великая стена, небоскрёбы Шанхая и тропический Хайнань. Древнейшая цивилизация с футуристическим настоящим.",
        "hero_subtitle_en": "The Great Wall, Shanghai skyscrapers, and tropical Hainan. Ancient civilization meets the future.",
        "advantages_ru": [
            ("🏛", "История и культура", "5000 лет истории. Великая стена, Запретный город, Терракотовая армия. 56 объектов ЮНЕСКО."),
            ("🏖", "Хайнань — тропический рай", "Китайские Гавайи. Песчаные пляжи, пальмы. +25°C круглый год."),
            ("🏙", "Футуристические города", "Шанхай — город будущего. Пекин — синтез древности и современности."),
            ("🚄", "Скоростные поезда", "Пекин–Шанхай за 4.5 часа. Крупнейшая сеть в мире."),
            ("🍜", "Гастрономия", "8 региональных кухонь. Утка по-пекински, дим-самы, сычуань."),
        ],
        "advantages_en": [
            ("🏛", "History & Culture", "5000 years. Great Wall, Forbidden City, Terracotta Army. 56 UNESCO sites."),
            ("🏖", "Hainan — Tropical Paradise", "China's Hawaii. Sandy beaches, +25°C year-round."),
            ("🏙", "Futuristic Cities", "Shanghai & Beijing — ancient meets modern."),
            ("🚄", "High-Speed Trains", "Beijing–Shanghai in 4.5 hours."),
            ("🍜", "Gastronomy", "8 regional cuisines. Peking duck, dim sum."),
        ],
        "seasons_ru": [
            ("🌸", "Весна (март–май)", "+10–22°C (север)", "Лучшее время для экскурсий. Хайнань — идеально."),
            ("🍂", "Осень (сентябрь–ноябрь)", "+10–20°C (север)", "Лучше всего для Пекина и Сианя. Комфортно, сухо."),
            ("☀️", "Лето (июнь–август)", "+25–35°C", "Жарко. Хайнань — высокий сезон."),
            ("❄️", "Зима (декабрь–февраль)", "−5…+5°C (север), +22–27°C (Хайнань)", "Хайнань — идеальное зимнее направление."),
        ],
        "seasons_en": [
            ("🌸", "Spring (Mar–May)", "+10–22°C (north)", "Best for sightseeing."),
            ("🍂", "Autumn (Sep–Nov)", "+10–20°C (north)", "Best for Beijing & Xi'an."),
            ("☀️", "Summer (Jun–Aug)", "+25–35°C", "Hot. Hainan high season."),
            ("❄️", "Winter (Dec–Feb)", "−5…+5°C (north)", "Hainan: ideal winter escape."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽70 000–120 000", ["Гестхаус: от ₽1 500/ночь", "Уличная еда: от ₽200/чел", "Метро, автобусы", "Бесплатные парки"]),
            ("💎 Комфорт", "₽150 000–300 000", ["Отель 4*: от ₽5 000/ночь", "Рестораны: от ₽1 000/чел", "Скоростные поезда 1-м классом", "Великая стена, Запретный город"]),
            ("👑 Премиум", "₽400 000+", ["Отель 5*: от ₽12 000/ночь", "Fine dining, частный гид", "VIP-туры", "Бизнес-класс на поездах"]),
        ],
        "budget_en": [
            ("💰 Economy", "$700–1 200", ["Guesthouse from $15/night", "Street food from $2/person", "Metro, buses", "Free parks"]),
            ("💎 Comfort", "$1 500–3 000", ["4* hotel from $50/night", "Restaurants from $10/person", "1st class trains", "Great Wall, Forbidden City"]),
            ("👑 Premium", "$4 000+", ["5* hotel from $120/night", "Fine dining, private guide", "VIP tours", "Business class trains"]),
        ],
        "practical_ru": {
            "visa": "Виза требуется. Хайнань — безвизовый въезд до 30 дней через туроператора.",
            "currency": "Китайский юань (CNY). Ориентировочно: 1 CNY ≈ 13.5 рублей (июнь 2026). WeChat/Alipay — основные способы оплаты.",
            "language": "Китайский. Английский — в отелях. Русский — на Хайнане. Рекомендуется переводчик.",
            "transport": "Скоростные поезда, метро, такси (Didi). Внутренние рейсы.",
            "safety": "Очень безопасно. VPN обязателен (Google, WhatsApp заблокированы).",
            "internet": "VPN обязателен. Местная SIM — от $10. Wi-Fi в отелях.",
        },
        "practical_en": {
            "visa": "Visa required. Hainan: visa-free 30 days via tour operator.",
            "currency": "CNY. WeChat/Alipay — primary payment. Cash recommended.",
            "language": "Mandarin. English in hotels. Translator app essential.",
            "transport": "High-speed trains, metro, taxi (Didi). Domestic flights.",
            "safety": "Very safe. VPN mandatory (Google, WhatsApp blocked).",
            "internet": "VPN mandatory. Local SIM from $10. Wi-Fi in hotels.",
        },
        "faq_ru": [
            ("Нужна ли виза в Китай?", "Да. Для Хайнаня — безвизовый въезд до 30 дней через туроператора."),
            ("Нужен ли QR-код здоровья?", "Да. WeChat/Alipay. Заполнить Health Kit. Обновлять ежедневно."),
            ("Нужен ли VPN?", "Да, обязателен. Установите до прилёта."),
            ("Когда лучше ехать?", "Для Пекина/Сианя: весна и осень. Для Хайнаня: ноябрь–апрель."),
            ("Сколько стоит отдых?", "Эконом: от ₽70 000. Комфорт: от ₽150 000. Премиум: от ₽400 000."),
            ("Что посмотреть?", "Великая стена, Запретный город, Вайтань, Терракотовая армия, Хайнань."),
        ],
        "faq_en": [
            ("Visa?", "Yes. Hainan: visa-free 30 days via tour operator."),
            ("Health QR code?", "Yes. WeChat/Alipay Health Kit. Update daily."),
            ("VPN?", "Yes, mandatory. Install before arrival."),
            ("When to visit?", "Beijing/Xi'an: spring & autumn. Hainan: November–April."),
            ("How much?", "Economy: from $700. Comfort: from $1 500. Premium: from $4 000."),
            ("What to see?", "Great Wall, Forbidden City, The Bund, Terracotta Army, Hainan."),
        ],
        "what_to_see_ru": ["Великая Китайская стена", "Запретный город (Пекин)", "Терракотовая армия (Сиань)", "Набережная Вайтань (Шанхай)", "Пляжи Саньи (Хайнань)", "Парк Чжанцзяцзе"],
        "what_to_see_en": ["Great Wall", "Forbidden City (Beijing)", "Terracotta Army (Xi'an)", "The Bund (Shanghai)", "Sanya beaches (Hainan)", "Zhangjiajie Park"],
        "where_to_stay_ru": [
            ("Вангфуджин (Пекин)", "Исторический центр. Отели 4–5* от ¥400/ночь."),
            ("Пудун (Шанхай)", "Деловой район. Отели 5* от ¥600/ночь."),
            ("Дадунхай (Санья)", "Пляжный район Хайнаня. Отели 4–5* от ¥300/ночь."),
        ],
        "where_to_stay_en": [
            ("Wangfujing (Beijing)", "Historic center. 4–5* from ¥400/night."),
            ("Pudong (Shanghai)", "Business district. 5* from ¥600/night."),
            ("Dadonghai (Sanya)", "Hainan beach. 4–5* from ¥300/night."),
        ],
    },
    "maldives": {
        "hero_subtitle_ru": "Бирюзовые лагуны, белоснежный песок и бунгало над водой. 26 атоллов в Индийском океане — райский отдых.",
        "hero_subtitle_en": "Turquoise lagoons, white sand, and overwater bungalows. 26 atolls in the Indian Ocean — paradise.",
        "advantages_ru": [
            ("🏝", "Уединение и романтика", "Один остров — один отель. Полная приватность. Идеально для пар и медового месяца."),
            ("🤿", "Дайвинг и снорклинг", "Богатейшие коралловые рифы мира. Манты, китовые акулы. Видимость до 40 м."),
            ("🏨", "Водные виллы", "Бунгало на сваях с доступом к океану. Стеклянный пол. Частный бассейн."),
            ("🧘", "Спа и оздоровление", "Спа мирового уровня. Подводные спа, массаж на песке, полный digital detox."),
            ("🌅", "Природа и закаты", "Биолюминесцентный планктон. Дельфины, скаты у берега."),
        ],
        "advantages_en": [
            ("🏝", "Seclusion & Romance", "One island — one hotel. Complete privacy."),
            ("🤿", "Diving & Snorkeling", "World's richest reefs. Mantas, whale sharks."),
            ("🏨", "Overwater Villas", "Bungalows with ocean access. Glass floor."),
            ("🧘", "Spa & Wellness", "World-class spas. Underwater spa. Digital detox."),
            ("🌅", "Nature & Sunsets", "Bioluminescent plankton. Dolphins by shore."),
        ],
        "seasons_ru": [
            ("☀️", "Сухой сезон (декабрь–апрель)", "+28–32°C", "Высокий сезон. Идеальная погода. Бронировать за 4–6 месяцев."),
            ("🌧", "Влажный сезон (май–ноябрь)", "+27–30°C", "Кратковременные ливни. Цены на 30–50% ниже."),
        ],
        "seasons_en": [
            ("☀️", "Dry Season (Dec–Apr)", "+28–32°C", "High season. Book 4–6 months ahead."),
            ("🌧", "Wet Season (May–Nov)", "+27–30°C", "Short showers. 30–50% cheaper."),
        ],
        "budget_ru": [
            ("💰 Эконом", "₽120 000–180 000", ["Гестхаус на локальном острове: от ₽2 500/ночь", "Местные кафе: от ₽500/чел", "Паромы от $2", "Экскурсии с локальными операторами"]),
            ("💎 Комфорт", "₽250 000–500 000", ["Курорт 4*: от ₽15 000/ночь", "Рестораны курорта", "Скоростной катер", "Дайвинг-туры, спа"]),
            ("👑 Премиум", "₽700 000+", ["Курорт 5* Deluxe: от ₽50 000/ночь", "Fine dining, батлер", "Гидросамолёт", "Вертолёт, подводный ресторан"]),
        ],
        "budget_en": [
            ("💰 Economy", "$1 200–1 800", ["Guesthouse from $25/night", "Local cafes from $5/person", "Ferries from $2", "Local operator excursions"]),
            ("💎 Comfort", "$2 500–5 000", ["4* resort from $150/night", "Resort restaurants", "Speedboat transfer", "Diving, spa"]),
            ("👑 Premium", "$7 000+", ["5* Deluxe from $500/night", "Fine dining, butler", "Seaplane transfer", "Helicopter, underwater restaurant"]),
        ],
        "practical_ru": {
            "visa": "Бесплатная виза по прибытии на 30 дней для всех. Загранпаспорт 6+ месяцев.",
            "currency": "Мальдивская руфия (MVR). Доллары везде. Наличные — на локальных островах.",
            "language": "Дивехи (официальный). Английский на всех курортах.",
            "transport": "Паромы, скоростные катера, гидросамолёты. На курортах — велосипеды.",
            "safety": "Очень безопасно. Солнцезащитный крем обязателен. Не трогайте кораллы.",
            "internet": "Wi-Fi на курортах. Местная SIM — от $10.",
        },
        "practical_en": {
            "visa": "Free visa on arrival, 30 days. All nationalities.",
            "currency": "Maldivian Rufiyaa. USD everywhere. Cash on local islands.",
            "language": "Dhivehi. English at all resorts.",
            "transport": "Ferries, speedboats, seaplanes.",
            "safety": "Very safe. Sunscreen essential. Don't touch coral.",
            "internet": "Wi-Fi at resorts. Local SIM from $10.",
        },
        "faq_ru": [
            ("Нужна ли виза на Мальдивы?", "Бесплатная виза по прибытии на 30 дней для всех."),
            ("Когда лучше ехать?", "Декабрь–апрель — сухой сезон. Май–ноябрь — дешевле на 30–50%."),
            ("Сколько стоит отдых?", "Мальдивы — не бюджет. Эконом: от ₽120 000. Комфорт: от ₽250 000. Премиум: от ₽700 000."),
            ("Можно ли бюджетно?", "Да, на локальных островах: гестхаусы от $25/ночь."),
            ("Что взять с собой?", "Солнцезащитный крем, коралловые тапочки, адаптер UK-типа G."),
            ("Нужен ли гидросамолёт?", "Только для удалённых курортов. Локальные острова — на пароме."),
        ],
        "faq_en": [
            ("Visa?", "Free visa on arrival, 30 days, all citizens."),
            ("When to visit?", "December–April dry season. May–November 30–50% cheaper."),
            ("How much?", "Not budget. Economy: from $1 200. Comfort: from $2 500. Premium: from $7 000."),
            ("Budget option?", "Yes, local islands: guesthouses from $25/night."),
            ("What to bring?", "Sunscreen, reef shoes, UK-type G adapter."),
            ("Seaplane needed?", "Only for remote resorts. Local islands by ferry."),
        ],
        "what_to_see_ru": ["Подводный ресторан Ithaa", "Биолюминесцентный пляж (Ваадхоо)", "Песчаная коса Дигура", "Сёрф-спот Чикенс", "Рыбный рынок Мале", "Дайвинг с мантами"],
        "what_to_see_en": ["Underwater restaurant Ithaa", "Bioluminescent beach (Vaadhoo)", "Dhigurah sandbank", "Chickens surf break", "Male Fish Market", "Manta diving"],
        "where_to_stay_ru": [
            ("Маафуши", "Самый популярный локальный остров. Гестхаусы от $25/ночь."),
            ("Хулхумале", "Рядом с аэропортом. Отели от $60/ночь."),
            ("Южный Мале Атолл", "Премиум-курорты: Anantara, Naladhu. От $400/ночь."),
        ],
        "where_to_stay_en": [
            ("Maafushi", "Most popular local island. Guesthouses from $25/night."),
            ("Hulhumale", "Near airport. Hotels from $60/night."),
            ("South Male Atoll", "Premium resorts: Anantara, Naladhu. From $400/night."),
        ],
    },
}

AGENT_PHOTO = "/assets/agent/photo_2026-06-06_00-51-06.webp"
AGENT_PHOTOS = [
    "/assets/agent/photo_2026-06-06_00-51-06.webp",
    "/assets/agent/photo_2026-06-06_00-51-10.webp",
    "/assets/agent/photo_2026-06-06_00-51-17.webp",
    "/assets/agent/photo_2026-06-06_00-51-44.webp",
    "/assets/agent/photo_2026-06-06_00-51-49.webp",
    "/assets/agent/photo_2026-06-06_00-51-53.webp",
    "/assets/agent/photo_2026-06-06_00-51-58.webp",
    "/assets/agent/photo_2026-06-06_00-52-01.webp",
    "/assets/agent/photo_2026-06-06_00-52-05.webp",
]

AGENT_NAME = "TravelHub Experts"
AGENT_NAME_EN = "TravelHub Experts"
AGENT_EMAIL = "i@turkov-1.ru"
AGENT_DESC_RU = "Команда TravelHub. Мы исследуем направления по всему миру и делимся честными гайдами. Помогаем путешественникам экономить на билетах, выбирать лучшие отели и уверенно планировать поездки. Все цены ориентировочные — всегда сверяйтесь с сайтами партнёров. Нужна помощь? Свяжитесь с нами — поможем организовать идеальный отдых."
AGENT_DESC_EN = "TravelHub team: We research destinations worldwide and share honest travel guides. We help travelers save on flights, choose the best hotels, and plan confidently. All prices are approximate — always check rates on partner sites. Need help? Contact us — we'll help you plan the perfect trip."
