DESTINATIONS = {
    "turkey": {
        "name_ru": "Турция",
        "name_en": "Turkey",
        "slug": "turkey",
        "currency": "TRY",
        "visa_ru": "безвизовый въезд для граждан РФ",
        "visa_en": "visa-free for Russian citizens",
        "airport_code": "IST",
        "cities": {
            "istanbul": {
                "name_ru": "Стамбул",
                "name_en": "Istanbul",
                "slug": "istanbul",
                "airport_codes": ["IST", "SAW"],
                "lat": 41.0082, "lon": 28.9784,
            },
            "antalya": {
                "name_ru": "Анталья",
                "name_en": "Antalya",
                "slug": "antalya",
                "airport_codes": ["AYT"],
                "lat": 36.8969, "lon": 30.7133,
            },
            "alanya": {
                "name_ru": "Аланья",
                "name_en": "Alanya",
                "slug": "alanya",
                "airport_codes": ["GZP"],
                "lat": 36.5440, "lon": 31.9954,
            },
            "bodrum": {
                "name_ru": "Бодрум",
                "name_en": "Bodrum",
                "slug": "bodrum",
                "airport_codes": ["BJV"],
                "lat": 37.0344, "lon": 27.4305,
            },
            "cappadocia": {
                "name_ru": "Каппадокия",
                "name_en": "Cappadocia",
                "slug": "cappadocia",
                "airport_codes": ["ASR", "NAV"],
                "lat": 38.6431, "lon": 34.8306,
            },
        },
    },
    "thailand": {
        "name_ru": "Таиланд",
        "name_en": "Thailand",
        "slug": "thailand",
        "currency": "THB",
        "visa_ru": "безвизовый въезд до 30 дней",
        "visa_en": "visa-free entry for up to 30 days",
        "airport_code": "BKK",
        "cities": {
            "bangkok": {
                "name_ru": "Бангкок",
                "name_en": "Bangkok",
                "slug": "bangkok",
                "airport_codes": ["BKK", "DMK"],
                "lat": 13.7563, "lon": 100.5018,
            },
            "phuket": {
                "name_ru": "Пхукет",
                "name_en": "Phuket",
                "slug": "phuket",
                "airport_codes": ["HKT"],
                "lat": 7.8804, "lon": 98.3923,
            },
            "pattaya": {
                "name_ru": "Паттайя",
                "name_en": "Pattaya",
                "slug": "pattaya",
                "airport_codes": ["UTP"],
                "lat": 12.9333, "lon": 100.8833,
            },
            "koh-samui": {
                "name_ru": "Самуи",
                "name_en": "Koh Samui",
                "slug": "koh-samui",
                "airport_codes": ["USM"],
                "lat": 9.5120, "lon": 100.0136,
            },
            "krabi": {
                "name_ru": "Краби",
                "name_en": "Krabi",
                "slug": "krabi",
                "airport_codes": ["KBV"],
                "lat": 8.0863, "lon": 98.9063,
            },
        },
    },
    "egypt": {
        "name_ru": "Египет",
        "name_en": "Egypt",
        "slug": "egypt",
        "currency": "EGP",
        "visa_ru": "виза по прибытии ($25)",
        "visa_en": "visa on arrival ($25)",
        "airport_code": "SSH",
        "cities": {
            "sharm-el-sheikh": {
                "name_ru": "Шарм-эль-Шейх",
                "name_en": "Sharm El Sheikh",
                "slug": "sharm-el-sheikh",
                "airport_codes": ["SSH"],
                "lat": 27.9158, "lon": 34.3300,
            },
            "hurghada": {
                "name_ru": "Хургада",
                "name_en": "Hurghada",
                "slug": "hurghada",
                "airport_codes": ["HRG"],
                "lat": 27.2579, "lon": 33.8116,
            },
            "cairo": {
                "name_ru": "Каир",
                "name_en": "Cairo",
                "slug": "cairo",
                "airport_codes": ["CAI"],
                "lat": 30.0444, "lon": 31.2357,
            },
            "luxor": {
                "name_ru": "Луксор",
                "name_en": "Luxor",
                "slug": "luxor",
                "airport_codes": ["LXR"],
                "lat": 25.6872, "lon": 32.6396,
            },
            "marsa-alam": {
                "name_ru": "Марса-Алам",
                "name_en": "Marsa Alam",
                "slug": "marsa-alam",
                "airport_codes": ["RMF"],
                "lat": 25.0671, "lon": 34.8900,
            },
        },
    },
    "uae": {
        "name_ru": "ОАЭ",
        "name_en": "UAE",
        "slug": "uae",
        "currency": "AED",
        "visa_ru": "безвизовый въезд до 90 дней",
        "visa_en": "visa-free entry for up to 90 days",
        "airport_code": "DXB",
        "cities": {
            "dubai": {
                "name_ru": "Дубай",
                "name_en": "Dubai",
                "slug": "dubai",
                "airport_codes": ["DXB"],
                "lat": 25.2048, "lon": 55.2708,
            },
            "abu-dhabi": {
                "name_ru": "Абу-Даби",
                "name_en": "Abu Dhabi",
                "slug": "abu-dhabi",
                "airport_codes": ["AUH"],
                "lat": 24.4539, "lon": 54.3773,
            },
            "sharjah": {
                "name_ru": "Шарджа",
                "name_en": "Sharjah",
                "slug": "sharjah",
                "airport_codes": ["SHJ"],
                "lat": 25.3225, "lon": 55.4197,
            },
            "ras-al-khaimah": {
                "name_ru": "Рас-эль-Хайма",
                "name_en": "Ras Al Khaimah",
                "slug": "ras-al-khaimah",
                "airport_codes": ["RKT"],
                "lat": 25.8007, "lon": 55.9762,
            },
            "fujairah": {
                "name_ru": "Фуджейра",
                "name_en": "Fujairah",
                "slug": "fujairah",
                "airport_codes": ["FJR"],
                "lat": 25.1288, "lon": 56.3265,
            },
        },
    },
    "indonesia": {
        "name_ru": "Индонезия",
        "name_en": "Indonesia",
        "slug": "indonesia",
        "currency": "IDR",
        "visa_ru": "виза по прибытии (500 000 IDR)",
        "visa_en": "visa on arrival (500,000 IDR)",
        "airport_code": "DPS",
        "cities": {
            "ubud": {
                "name_ru": "Убуд",
                "name_en": "Ubud",
                "slug": "ubud",
                "airport_codes": ["DPS"],
                "lat": -8.5069, "lon": 115.2625,
            },
            "kuta": {
                "name_ru": "Кута",
                "name_en": "Kuta",
                "slug": "kuta",
                "airport_codes": ["DPS"],
                "lat": -8.7233, "lon": 115.1725,
            },
            "seminyak": {
                "name_ru": "Семиньяк",
                "name_en": "Seminyak",
                "slug": "seminyak",
                "airport_codes": ["DPS"],
                "lat": -8.6914, "lon": 115.1550,
            },
            "canggu": {
                "name_ru": "Чангу",
                "name_en": "Canggu",
                "slug": "canggu",
                "airport_codes": ["DPS"],
                "lat": -8.6478, "lon": 115.1386,
            },
            "nusa-dua": {
                "name_ru": "Нуса-Дуа",
                "name_en": "Nusa Dua",
                "slug": "nusa-dua",
                "airport_codes": ["DPS"],
                "lat": -8.8060, "lon": 115.2333,
            },
        },
    },
    "china": {
        "name_ru": "Китай",
        "name_en": "China",
        "slug": "china",
        "currency": "CNY",
        "visa_ru": "виза требуется (оформление через туроператора). Для Хайнаня — безвизовый въезд до 30 дней через туроператора. Обязателен QR-код здоровья (WeChat/Alipay).",
        "visa_en": "visa required (processed via tour operator). Hainan — visa-free up to 30 days via tour operator. Health QR code required (WeChat/Alipay).",
        "airport_code": "SYX",
        "cities": {
            "sanya": {
                "name_ru": "Санья (Хайнань)",
                "name_en": "Sanya (Hainan)",
                "slug": "sanya",
                "airport_codes": ["SYX"],
                "lat": 18.2528, "lon": 109.5120,
            },
            "haikou": {
                "name_ru": "Хайкоу (Хайнань)",
                "name_en": "Haikou (Hainan)",
                "slug": "haikou",
                "airport_codes": ["HAK"],
                "lat": 20.0174, "lon": 110.3492,
            },
            "beijing": {
                "name_ru": "Пекин",
                "name_en": "Beijing",
                "slug": "beijing",
                "airport_codes": ["PEK", "PKX"],
                "lat": 39.9042, "lon": 116.4074,
            },
            "shanghai": {
                "name_ru": "Шанхай",
                "name_en": "Shanghai",
                "slug": "shanghai",
                "airport_codes": ["PVG", "SHA"],
                "lat": 31.2304, "lon": 121.4737,
            },
            "xian": {
                "name_ru": "Сиань",
                "name_en": "Xi'an",
                "slug": "xian",
                "airport_codes": ["XIY"],
                "lat": 34.3416, "lon": 108.9398,
            },
        },
    },
}
